apiVersion: apps/v1
kind: Deployment
metadata:
    name: php
spec:
    replicas: 3
    selector:
        matchLabels:
            app: php
    template:
        metadata:
            labels:
                app: php
        spec:
            containers:
                - name: php
                  image: adamcameron/php8-on-k8s:latest
                  ports:
                      - containerPort: 9000
                  envFrom:
                      - configMapRef:
                            name: php-config
                      - secretRef:
                            name: php-secret
                  env:
                    - name: POD_NAME
                      valueFrom:
                        fieldRef:
                          fieldPath: metadata.name
                    - name: CONTAINER_NAME
                      value: php
            restartPolicy: Always
