services:
  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile

    ports:
      - "8080:80"

    stdin_open: true
    tty: true

    volumes:
      - ../public:/usr/share/nginx/html/

    depends_on:
      - php

  php:
    build:
      context: php
      dockerfile: Dockerfile

    stdin_open: true
    tty: true

    volumes:
      - ..:/var/www
